# CI for Coconut, using Github Actions.

name: CIfmt

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  Ubuntu:
    name: CI-run-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Run clang-fmt
        shell: bash -l {0}
        run: >-
          bash scripts/clang_fmt_lint.sh --check-only

      - name: Build sources
        shell: bash -l {0}
        run: >-
          mkdir build
          cd build
          cmake ..
          make

      - name: Run gtest
        shell: bash -l {0}
        run: >-
          build/cocotest
