# CI for Coconut, using Github Actions.

name: Coconut-CI-Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  Ubuntu:
    name: Coconut-CI-Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run clang-format
        shell: bash -l {0}
        run: >-
          bash scripts/clang_fmt_lint.sh --check-only

      - name: Build sources
        shell: bash -l {0}
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run GTest
        shell: bash -l {0}
        run: >-
          ./cocotest
